# Generated by Django 4.0.5 on 2022-07-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productimage_images_basket_uniq_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='privileged_attribute',
            field=models.ManyToManyField(related_name='privileged_att', to='shop.attribute'),
        ),
    ]
