# Generated by Django 4.0.5 on 2022-08-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_variation_privileged_attribute'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attribute',
            constraint=models.UniqueConstraint(fields=('name', 'value'), name='unique_attribute'),
        ),
    ]
