# Generated by Django 4.0.5 on 2022-09-08 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_orderitem_in_basket_orderitem_attribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='privileged_attribute',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.variation'),
        ),
    ]
